package ch.fhnw.meeting.model.feedback;

public enum IssueTag {
    NO_CLEAR_AGENDA, TOO_LONG, TOO_MANY_PARTICIPANTS,
    NOT_RELEVANT_FOR_ME, COULD_HAVE_BEEN_ASYNC,
    NO_DECISIONS_OR_NEXT_STEPS, POOR_PREPARATION,
    SCOPE_TOO_BROAD, DOMINATED_BY_FEW, TECHNICAL_ISSUES,
    TOO_CLOSE_TO_ANOTHER, NO_RECOVER_TIME, LACK_OF_FOCUS
}