package ch.fhnw.meeting.model.feedback;

public enum PositiveTag {
    EFFICIENT_STRUCTURED, PROVIDED_INFO, GOOD_PREPARATION,
    CLEAR_DECISIONS, RELEVANT_TOPICS, ACTIVE_PARTICIPATION,
    GOOD_MODERATION, WELL_PRACTICED, GOOD_ENERGY
}
